M48
; DRILL file {KiCad 7.0.7} date Tue Oct 17 17:05:37 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-17T17:05:37-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X150.493Y-66.819
X157.493Y-66.819
T2
X168.669Y-81.349
X182.005Y-103.829
T0
M30
